# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------
# pylint: disable=line-too-long

from azure.cli.testsdk import ScenarioTest


# Test class for Scenario
class PositiveTest(ScenarioTest):

    def __init__(self, *args, **kwargs):
        super(PositiveTest, self).__init__(*args, **kwargs)

    # EXAMPLE: /ManagedNetworks/get/ManagedNetworksListByResourceGroup
    def test_mn_list(self):
        self.cmd('az managed-network mn list '
                 '--resource-group "myResourceGroup"')

    # EXAMPLE: /ManagedNetworks/get/ManagedNetworksListBySubscription
    def test_mn_list2(self):
        self.cmd('az managed-network mn list')

    # EXAMPLE: /ManagedNetworks/put/ManagedNetworksPut
    def test_mn_create(self):
        self.cmd('az managed-network mn create '
                 '--managed-network "{{\\"location\\":\\"eastus\\",\\"tags\\":{{}},\\"managementGroups\\":[{{\\"id\\":\\"/providers/Microsoft.Management/managementGroups/20000000-0001-0000-0000-000000000000\\"}},{{\\"id\\":\\"/providers/Microsoft.Management/managementGroups/20000000-0002-0000-0000-000000000000\\"}}],\\"subscriptions\\":[{{\\"id\\":\\"subscriptionA\\"}},{{\\"id\\":\\"subscriptionB\\"}}],\\"virtualNetworks\\":[{{\\"id\\":\\"/subscriptions/subscriptionC/resourceGroups/myResourceGroup/providers/Microsoft.Network/virtualNetworks/myVirtualNetwork\\"}},{{\\"id\\":\\"/subscriptions/subscriptionC/resourceGroups/myResourceGroup/providers/Microsoft.Network/virtualNetworks/myVirtualNetwork2\\"}}],\\"subnets\\":[{{\\"id\\":\\"/subscriptions/subscriptionC/resourceGroups/myResourceGroup/providers/Microsoft.Network/virtualNetworks/myVirtualNetwork3/subnets/mySubnet\\"}},{{\\"id\\":\\"/subscriptions/subscriptionC/resourceGroups/myResourceGroup/providers/Microsoft.Network/virtualNetworks/myVirtualNetwork3/subnets/mySubnet2\\"}}]}}" '
                 '--name "myManagedNetwork" '
                 '--resource-group "myResourceGroup"')

    # EXAMPLE: /ManagedNetworks/patch/ManagedNetworksPatch
    def test_mn_update(self):
        self.cmd('az managed-network mn update '
                 '--name "myManagedNetwork" '
                 '--resource-group "myResourceGroup"')

    # EXAMPLE: /ManagedNetworks/delete/ManagedNetworksDelete
    def test_mn_delete(self):
        self.cmd('az managed-network mn delete -y '
                 '--name "myManagedNetwork" '
                 '--resource-group "myResourceGroup"')

    # EXAMPLE: /ManagedNetworks/get/ManagedNetworksGet
    def test_mn_show_modify(self):
        self.cmd('az managed-network mn show-modify '
                 '--name "myManagedNetwork" '
                 '--resource-group "myResourceGroup"')

    # EXAMPLE: /ScopeAssignments/get/ScopeAssignmentsList
    def test_mn_scope_assignment_list(self):
        self.cmd('az managed-network mn scope-assignment list '
                 '--scope "subscriptions/subscriptionC"')

    # EXAMPLE: /ScopeAssignments/get/ScopeAssignmentsGet
    def test_mn_scope_assignment_show(self):
        self.cmd('az managed-network mn scope-assignment show '
                 '--scope "subscriptions/subscriptionC" '
                 '--name "myScopeAssignment"')

    # EXAMPLE: /ScopeAssignments/put/ScopeAssignmentsPut
    def test_mn_scope_assignment_create(self):
        self.cmd('az managed-network mn scope-assignment create '
                 '--assigned-managed-network "/subscriptions/subscriptionA/resourceGroups/myResourceGroup/providers/Microsoft.ManagedNetwork/managedNetworks/myManagedNetwork" '
                 '--scope "subscriptions/subscriptionC" '
                 '--name "myScopeAssignment"')

    # EXAMPLE: /ScopeAssignments/delete/ScopeAssignmentsDelete
    def test_mn_scope_assignment_delete(self):
        self.cmd('az managed-network mn scope-assignment delete -y '
                 '--scope "subscriptions/subscriptionC" '
                 '--name "myScopeAssignment"')

    # EXAMPLE: /ManagedNetworkGroups/get/ManagedNetworksGroupsListByManagedNetwork
    def test_mn_group_list(self):
        self.cmd('az managed-network mn group list '
                 '--managed-network-name "myManagedNetwork" '
                 '--resource-group "myResourceGroup"')

    # EXAMPLE: /ManagedNetworkGroups/get/ManagementNetworkGroupsGet
    def test_mn_group_show(self):
        self.cmd('az managed-network mn group show '
                 '--group-name "myManagedNetworkGroup" '
                 '--managed-network-name "myManagedNetwork" '
                 '--resource-group "myResourceGroup"')

    # EXAMPLE: /ManagedNetworkGroups/put/ManagementNetworkGroupsPut
    def test_mn_group_create(self):
        self.cmd('az managed-network mn group create '
                 '--management-groups "[]" '
                 '--subnets id="/subscriptions/subscriptionB/resourceGroups/myResourceGroup/providers/Microsoft.Network/virtualNetworks/myVirtualNetwork/subnets/mySubnet" id="/subscriptions/subscriptionB/resourceGroups/myResourceGroup/providers/Microsoft.Network/virtualNetworks/myVirtualNetwork2/subnets/mySubnet2" '
                 '--virtual-networks id="/subscriptionB/resourceGroups/myResourceGroup/providers/Microsoft.Network/virtualNetworks/VnetA" '
                 '--virtual-networks id="/subscriptionB/resourceGroups/myResourceGroup/providers/Microsoft.Network/virtualNetworks/VnetB" '
                 '--group-name "myManagedNetworkGroup" '
                 '--managed-network-name "myManagedNetwork" '
                 '--resource-group "myResourceGroup"')

    # EXAMPLE: /ManagedNetworkGroups/delete/ManagementNetworkGroupsDelete
    def test_mn_group_delete(self):
        self.cmd('az managed-network mn group delete -y '
                 '--group-name "myManagedNetworkGroup" '
                 '--managed-network-name "myManagedNetwork" '
                 '--resource-group "myResourceGroup"')

    # EXAMPLE: /ManagedNetworkPeeringPolicies/get/ManagedNetworkPeeringPoliciesListByManagedNetwork
    def test_managed_network_peering_policy_list(self):
        self.cmd('az managed-network managed-network-peering-policy list '
                 '--managed-network-name "myManagedNetwork" '
                 '--resource-group "myResourceGroup"')

    # EXAMPLE: /ManagedNetworkPeeringPolicies/get/ManagedNetworkPeeringPoliciesGet
    def test_managed_network_peering_policy_show(self):
        self.cmd('az managed-network managed-network-peering-policy show '
                 '--managed-network-name "myManagedNetwork" '
                 '--policy-name "myManagedNetworkPeeringPolicy" '
                 '--resource-group "myResourceGroup"')

    # EXAMPLE: /ManagedNetworkPeeringPolicies/put/ManagedNetworkPeeringPoliciesPut
    def test_managed_network_peering(self):
        self.cmd('az managed-network managed-network-peering-policy hub-and-spoke-topology create '
                 '--managed-network-name "myManagedNetwork" '
                 '--policy-name "myManagedNetworkPeeringPolicy" '
                 '--managed-network-policy "lslsd" '
                 '--hub id="/subscriptions/subscriptionB/resourceGroups/myResourceGroup/providers/Microsoft.Network/virtualNetworks/myVirtualNetwork4" '
                 '--spokes id="/subscriptions/subscriptionB/resourceGroups/myResourceGroup/providers/Microsoft.ManagedNetwork/managedNetworks/myManagedNetwork/managedNetworkGroups/myManagedNetworkGroup" '
                 '--resource-group "myResourceGroup"')

    # EXAMPLE: /ManagedNetworkPeeringPolicies/put/ManagedNetworkPeeringPoliciesPut
    def test_managed_network_peering(self):
        self.cmd('az managed-network managed-network-peering-policy hub-and-spoke-topology update '
                 '--managed-network-name "myManagedNetwork" '
                 '--policy-name "myManagedNetworkPeeringPolicy" '
                 '--managed-network-policy "lslsd" '
                 '--hub id="/subscriptions/subscriptionB/resourceGroups/myResourceGroup/providers/Microsoft.Network/virtualNetworks/myVirtualNetwork4" '
                 '--spokes id="/subscriptions/subscriptionB/resourceGroups/myResourceGroup/providers/Microsoft.ManagedNetwork/managedNetworks/myManagedNetwork/managedNetworkGroups/myManagedNetworkGroup" '
                 '--resource-group "myResourceGroup"')

    # EXAMPLE: /ManagedNetworkPeeringPolicies/delete/ManagedNetworkPeeringPoliciesDelete
    def test_managed_network_peering_policy_delete(self):
        self.cmd('az managed-network managed-network-peering-policy delete -y '
                 '--managed-network-name "myManagedNetwork" '
                 '--policy-name "myManagedNetworkPeeringPolicy" '
                 '--resource-group "myResourceGroup"')
