import { CodeModelAz } from "./CodeModelAz"

export function GenerateAzureCliTestPrepare(model: CodeModelAz) : string[] {
    var output: string[] = [];
    output.push("# --------------------------------------------------------------------------------------------");
    output.push("# Copyright (c) Microsoft Corporation. All rights reserved.");
    output.push("# Licensed under the MIT License. See License.txt in the project root for license information.");
    output.push("# --------------------------------------------------------------------------------------------");
    output.push("");
    output.push("import os");
    output.push("from datetime import datetime");
    output.push("from azure.cli.testsdk.preparers import NoTrafficRecordingPreparer");
    output.push("from azure_devtools.scenario_tests import SingleValueReplacer");
    output.push("from azure.cli.testsdk.exceptions import CliTestError");
    output.push("from azure.cli.testsdk.reverse_dependency import get_dummy_cli");
    output.push("");
    output.push("");
    output.push("KEY_RESOURCE_GROUP = 'rg'");
    output.push("KEY_VIRTUAL_NETWORK = 'vnet'");
    output.push("KEY_VNET_SUBNET = 'subnet'");
    output.push("");
    output.push("");
    output.push("class VirtualNetworkPreparer(NoTrafficRecordingPreparer, SingleValueReplacer):");
    output.push("    def __init__(self, name_prefix='clitest.vn',");
    output.push("                 parameter_name='virtual_network',");
    output.push("                 resource_group_name=None,");
    output.push("                 resource_group_key=KEY_RESOURCE_GROUP,");
    output.push("                 dev_setting_name='AZURE_CLI_TEST_DEV_VIRTUAL_NETWORK_NAME',");
    output.push("                 random_name_length=75, key=KEY_VIRTUAL_NETWORK):");
    output.push("        if ' ' in name_prefix:");
    output.push("            raise CliTestError(");
    output.push("                'Error: Space character in name prefix \\'%s\\'' % name_prefix)");
    output.push("        super(VirtualNetworkPreparer, self).__init__(");
    output.push("            name_prefix, random_name_length)");
    output.push("        self.cli_ctx = get_dummy_cli()");
    output.push("        self.parameter_name = parameter_name");
    output.push("        self.key = key");
    output.push("        self.resource_group_name = resource_group_name");
    output.push("        self.resource_group_key = resource_group_key");
    output.push("        self.dev_setting_name = os.environ.get(dev_setting_name, None)");
    output.push("");
    output.push("    def create_resource(self, name, **kwargs):");
    output.push("        if self.dev_setting_name:");
    output.push("            return {self.parameter_name: self.dev_setting_name, }");
    output.push("");
    output.push("        if not self.resource_group_name:");
    output.push("            self.resource_group_name = self.test_class_instance.kwargs.get(");
    output.push("                self.resource_group_key)");
    output.push("            if not self.resource_group_name:");
    output.push("                raise CliTestError(\"Error: No resource group configured!\")");
    output.push("");
    output.push("        tags = {'product': 'azurecli', 'cause': 'automation',");
    output.push("                'date': datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')}");
    output.push("        if 'ENV_JOB_NAME' in os.environ:");
    output.push("            tags['job'] = os.environ['ENV_JOB_NAME']");
    output.push("        tags = ' '.join(['{}={}'.format(key, value)");
    output.push("                         for key, value in tags.items()])");
    output.push("        template = 'az network vnet create --resource-group {} --name {} --tag ' + tags");
    output.push("        self.live_only_execute(self.cli_ctx, template.format(");
    output.push("            self.resource_group_name, name))");
    output.push("");
    output.push("        self.test_class_instance.kwargs[self.key] = name");
    output.push("        return {self.parameter_name: name}");
    output.push("");
    output.push("    def remove_resource(self, name, **kwargs):");
    output.push("        # delete vnet if test is being recorded and if the vnet is not a dev rg");
    output.push("        if not self.dev_setting_name:");
    output.push("            self.live_only_execute(");
    output.push("                self.cli_ctx, 'az network vnet delete --name {}'.format(name))");
    output.push("");
    output.push("");
    output.push("class VnetSubnetPreparer(NoTrafficRecordingPreparer, SingleValueReplacer):");
    output.push("    def __init__(self, name_prefix='clitest.vn',");
    output.push("                 parameter_name='virtual_network',");
    output.push("                 resource_group_name=None,");
    output.push("                 resource_group_key=KEY_RESOURCE_GROUP,");
    output.push("                 vnet_name=None,");
    output.push("                 vnet_key=KEY_VIRTUAL_NETWORK,");
    output.push("                 address_prefixes=\"11.0.0.0/24\",");
    output.push("                 dev_setting_name='AZURE_CLI_TEST_DEV_VNET_SUBNET_NAME',");
    output.push("                 random_name_length=75, key=KEY_VNET_SUBNET):");
    output.push("        if ' ' in name_prefix:");
    output.push("            raise CliTestError(");
    output.push("                'Error: Space character in name prefix \\'%s\\'' % name_prefix)");
    output.push("        super(VnetSubnetPreparer, self).__init__(");
    output.push("            name_prefix, random_name_length)");
    output.push("        self.cli_ctx = get_dummy_cli()");
    output.push("        self.parameter_name = parameter_name");
    output.push("        self.key = key");
    output.push("        self.resource_group_name = resource_group_name");
    output.push("        self.resource_group_key = resource_group_key");
    output.push("        self.vnet_name = vnet_name");
    output.push("        self.vnet_key = vnet_key");
    output.push("        self.address_prefixes = address_prefixes");
    output.push("        self.dev_setting_name = os.environ.get(dev_setting_name, None)");
    output.push("");
    output.push("    def create_resource(self, name, **kwargs):");
    output.push("        if self.dev_setting_name:");
    output.push("            return {self.parameter_name: self.dev_setting_name, }");
    output.push("");
    output.push("        if not self.resource_group_name:");
    output.push("            self.resource_group_name = self.test_class_instance.kwargs.get(");
    output.push("                self.resource_group_key)");
    output.push("            if not self.resource_group_name:");
    output.push("                raise CliTestError(\"Error: No resource group configured!\")");
    output.push("        if not self.vnet_name:");
    output.push("            self.vnet_name = self.test_class_instance.kwargs.get(self.vnet_key)");
    output.push("            if not self.vnet_name:");
    output.push("                raise CliTestError(\"Error: No vnet configured!\")");
    output.push("");
    output.push("        # tags = {'product': 'azurecli', 'cause': 'automation',");
    output.push("        #         'date': datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')}");
    output.push("        # if 'ENV_JOB_NAME' in os.environ:");
    output.push("        #     tags['job'] = os.environ['ENV_JOB_NAME']");
    output.push("        # tags = ' '.join(['{}={}'.format(key, value)");
    output.push("        #                  for key, value in tags.items()])");
    output.push("        template = \"az network vnet subnet create --resource-group {} \" \\");
    output.push("            \"--vnet-name {} --name {} --address-prefixes {}\"");
    output.push("        self.live_only_execute(self.cli_ctx, template.format(");
    output.push("            self.resource_group_name, self.vnet_name, name,");
    output.push("            self.address_prefixes))");
    output.push("");
    output.push("        self.test_class_instance.kwargs[self.key] = name");
    output.push("        return {self.parameter_name: name}");
    output.push("");
    output.push("    def remove_resource(self, name, **kwargs):");
    output.push("        # delete vnet if test is being recorded and if the vnet is not a dev rg");
    output.push("        if not self.dev_setting_name:");
    output.push("            self.live_only_execute(self.cli_ctx, \"az network vnet subnet\"");
    output.push("                                   \"delete --name {} --resource-group {} \"");
    output.push("                                   \"--vnet-name {}\".format(");
    output.push("                                       name, self.resource_group_name,");
    output.push("                                       self.vnet_name))");
    output.push("");
    return output;
}

