# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.0.6198, generator: {generator})
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from typing import Any, Optional

from azure.core import AsyncPipelineClient
from msrest import Deserializer, Serializer

from ._configuration_async import ManagedNetworkManagementClientConfiguration
from .operations_async import ManagedNetworksOperations
from .operations_async import ScopeAssignmentsOperations
from .operations_async import ManagedNetworkGroupsOperations
from .operations_async import ManagedNetworkPeeringPoliciesOperations
from .operations_async import Operations
from .. import models


class ManagedNetworkManagementClient(object):
    """The Microsoft Azure Managed Network management API provides a RESTful set of web services that interact with Microsoft Azure Networks service to programmatically view, control, change, and monitor your entire Azure network centrally and with ease.

    :ivar managed_networks: ManagedNetworksOperations operations
    :vartype managed_networks: managed_network_management_client.aio.operations_async.ManagedNetworksOperations
    :ivar scope_assignments: ScopeAssignmentsOperations operations
    :vartype scope_assignments: managed_network_management_client.aio.operations_async.ScopeAssignmentsOperations
    :ivar managed_network_groups: ManagedNetworkGroupsOperations operations
    :vartype managed_network_groups: managed_network_management_client.aio.operations_async.ManagedNetworkGroupsOperations
    :ivar managed_network_peering_policies: ManagedNetworkPeeringPoliciesOperations operations
    :vartype managed_network_peering_policies: managed_network_management_client.aio.operations_async.ManagedNetworkPeeringPoliciesOperations
    :ivar operations: Operations operations
    :vartype operations: managed_network_management_client.aio.operations_async.Operations
    :param credential: Credential needed for the client to connect to Azure.
    :type credential: azure.core.credentials.TokenCredential
    :param subscription_id: Gets subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
    :type subscription_id: str
    :param str base_url: Service URL
    """

    def __init__(
        self,
        credential: "TokenCredential",
        subscription_id: str,
        base_url: Optional[str] = None,
        **kwargs: Any
    ) -> None:
        if not base_url:
            base_url = 'https://management.azure.com'
        self._config = ManagedNetworkManagementClientConfiguration(credential, subscription_id, **kwargs)
        self._client = AsyncPipelineClient(base_url=base_url, config=self._config, **kwargs)

        client_models = {k: v for k, v in models.__dict__.items() if isinstance(v, type)}
        self._serialize = Serializer(client_models)
        self._deserialize = Deserializer(client_models)

        self.managed_networks = ManagedNetworksOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.scope_assignments = ScopeAssignmentsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.managed_network_groups = ManagedNetworkGroupsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.managed_network_peering_policies = ManagedNetworkPeeringPoliciesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.operations = Operations(
            self._client, self._config, self._serialize, self._deserialize)

    async def close(self) -> None:
        await self._client.close()

    async def __aenter__(self) -> "ManagedNetworkManagementClient":
        await self._client.__aenter__()
        return self

    async def __aexit__(self, *exc_details) -> None:
        await self._client.__aexit__(*exc_details)
