# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import AutoPauseProperties
    from ._models_py3 import AutoScaleProperties
    from ._models_py3 import AvailableRPOperation
    from ._models_py3 import AvailableRPOperationDisplayInfo
    from ._models_py3 import BigDataPoolPatchInfo
    from ._models_py3 import BigDataPoolResourceInfo
    from ._models_py3 import BigDataPoolResourceInfoListResult
    from ._models_py3 import CheckNameAvailabilityRequest
    from ._models_py3 import CheckNameAvailabilityResponse
    from ._models_py3 import CloudError
    from ._models_py3 import CmdkeySetup
    from ._models_py3 import ComponentSetup
    from ._models_py3 import CreateSQLPoolRestorePointDefinition
    from ._models_py3 import CustomSetupBase
    from ._models_py3 import DataLakeStorageAccountDetails
    from ._models_py3 import DataWarehouseUserActivities
    from ._models_py3 import EntityReference
    from ._models_py3 import EnvironmentVariableSetup
    from ._models_py3 import ErrorAdditionalInfo
    from ._models_py3 import ErrorContract
    from ._models_py3 import ErrorDetail
    from ._models_py3 import ErrorResponse
    from ._models_py3 import GeoBackupPolicy
    from ._models_py3 import GetSsisObjectMetadataRequest
    from ._models_py3 import IntegrationRuntime
    from ._models_py3 import IntegrationRuntimeAuthKeys
    from ._models_py3 import IntegrationRuntimeComputeProperties
    from ._models_py3 import IntegrationRuntimeConnectionInfo
    from ._models_py3 import IntegrationRuntimeCustomSetupScriptProperties
    from ._models_py3 import IntegrationRuntimeDataFlowProperties
    from ._models_py3 import IntegrationRuntimeDataProxyProperties
    from ._models_py3 import IntegrationRuntimeListResponse
    from ._models_py3 import IntegrationRuntimeMonitoringData
    from ._models_py3 import IntegrationRuntimeNodeIpAddress
    from ._models_py3 import IntegrationRuntimeNodeMonitoringData
    from ._models_py3 import IntegrationRuntimeRegenerateKeyParameters
    from ._models_py3 import IntegrationRuntimeResource
    from ._models_py3 import IntegrationRuntimeSsisCatalogInfo
    from ._models_py3 import IntegrationRuntimeSsisProperties
    from ._models_py3 import IntegrationRuntimeStatus
    from ._models_py3 import IntegrationRuntimeStatusResponse
    from ._models_py3 import IntegrationRuntimeVNetProperties
    from ._models_py3 import IpFirewallRuleInfo
    from ._models_py3 import IpFirewallRuleInfoListResult
    from ._models_py3 import IpFirewallRuleProperties
    from ._models_py3 import LibraryRequirements
    from ._models_py3 import LinkedIntegrationRuntime
    from ._models_py3 import LinkedIntegrationRuntimeKeyAuthorization
    from ._models_py3 import LinkedIntegrationRuntimeRbacAuthorization
    from ._models_py3 import LinkedIntegrationRuntimeType
    from ._models_py3 import ManagedIdentity
    from ._models_py3 import ManagedIdentitySQLControlSettingsModel
    from ._models_py3 import ManagedIdentitySQLControlSettingsModelPropertiesGrantSQLControlToManagedIdentity
    from ._models_py3 import ManagedIntegrationRuntime
    from ._models_py3 import ManagedIntegrationRuntimeError
    from ._models_py3 import ManagedIntegrationRuntimeNode
    from ._models_py3 import ManagedIntegrationRuntimeOperationResult
    from ._models_py3 import ManagedIntegrationRuntimeStatus
    from ._models_py3 import MetadataSyncConfig
    from ._models_py3 import OperationMetaLogSpecification
    from ._models_py3 import OperationMetaMetricDimensionSpecification
    from ._models_py3 import OperationMetaMetricSpecification
    from ._models_py3 import OperationMetaServiceSpecification
    from ._models_py3 import OperationResource
    from ._models_py3 import PrivateEndpoint
    from ._models_py3 import PrivateEndpointConnection
    from ._models_py3 import PrivateEndpointConnectionList
    from ._models_py3 import PrivateLinkHub
    from ._models_py3 import PrivateLinkHubInfoListResult
    from ._models_py3 import PrivateLinkHubPatchInfo
    from ._models_py3 import PrivateLinkResource
    from ._models_py3 import PrivateLinkResourceListResult
    from ._models_py3 import PrivateLinkResourceProperties
    from ._models_py3 import PrivateLinkServiceConnectionState
    from ._models_py3 import ProxyResource
    from ._models_py3 import QueryInterval
    from ._models_py3 import QueryMetric
    from ._models_py3 import QueryStatistic
    from ._models_py3 import ReplaceAllFirewallRulesOperationResponse
    from ._models_py3 import ReplaceAllIpFirewallRulesRequest
    from ._models_py3 import ReplicationLink
    from ._models_py3 import ReplicationLinkListResult
    from ._models_py3 import Resource
    from ._models_py3 import ResourceMoveDefinition
    from ._models_py3 import RestorePoint
    from ._models_py3 import RestorePointListResult
    from ._models_py3 import SQLPool
    from ._models_py3 import SQLPoolBlobAuditingPolicy
    from ._models_py3 import SQLPoolBlobAuditingPolicySQLPoolOperationListResult
    from ._models_py3 import SQLPoolColumn
    from ._models_py3 import SQLPoolColumnListResult
    from ._models_py3 import SQLPoolConnectionPolicy
    from ._models_py3 import SQLPoolInfoListResult
    from ._models_py3 import SQLPoolOperation
    from ._models_py3 import SQLPoolPatchInfo
    from ._models_py3 import SQLPoolSchema
    from ._models_py3 import SQLPoolSchemaListResult
    from ._models_py3 import SQLPoolSecurityAlertPolicy
    from ._models_py3 import SQLPoolTable
    from ._models_py3 import SQLPoolTableListResult
    from ._models_py3 import SQLPoolUsage
    from ._models_py3 import SQLPoolUsageListResult
    from ._models_py3 import SQLPoolVulnerabilityAssessment
    from ._models_py3 import SQLPoolVulnerabilityAssessmentListResult
    from ._models_py3 import SQLPoolVulnerabilityAssessmentRuleBaseline
    from ._models_py3 import SQLPoolVulnerabilityAssessmentRuleBaselineItem
    from ._models_py3 import SQLPoolVulnerabilityAssessmentScansExport
    from ._models_py3 import SecretBase
    from ._models_py3 import SecureString
    from ._models_py3 import SelfHostedIntegrationRuntime
    from ._models_py3 import SelfHostedIntegrationRuntimeNode
    from ._models_py3 import SelfHostedIntegrationRuntimeStatus
    from ._models_py3 import SensitivityLabel
    from ._models_py3 import SensitivityLabelListResult
    from ._models_py3 import Sku
    from ._models_py3 import SsisEnvironment
    from ._models_py3 import SsisEnvironmentReference
    from ._models_py3 import SsisFolder
    from ._models_py3 import SsisObjectMetadata
    from ._models_py3 import SsisObjectMetadataListResponse
    from ._models_py3 import SsisObjectMetadataStatusResponse
    from ._models_py3 import SsisPackage
    from ._models_py3 import SsisParameter
    from ._models_py3 import SsisProject
    from ._models_py3 import SsisVariable
    from ._models_py3 import SubResource
    from ._models_py3 import TopQueries
    from ._models_py3 import TopQueriesListResult
    from ._models_py3 import TrackedResource
    from ._models_py3 import TransparentDataEncryption
    from ._models_py3 import UpdateIntegrationRuntimeNodeRequest
    from ._models_py3 import UpdateIntegrationRuntimeRequest
    from ._models_py3 import VirtualNetworkProfile
    from ._models_py3 import VulnerabilityAssessmentRecurringScansProperties
    from ._models_py3 import VulnerabilityAssessmentScanError
    from ._models_py3 import VulnerabilityAssessmentScanRecord
    from ._models_py3 import VulnerabilityAssessmentScanRecordListResult
    from ._models_py3 import Workspace
    from ._models_py3 import WorkspaceAADAdminInfo
    from ._models_py3 import WorkspaceInfoListResult
    from ._models_py3 import WorkspacePatchInfo
except (SyntaxError, ImportError):
    from ._models import AutoPauseProperties  # type: ignore
    from ._models import AutoScaleProperties  # type: ignore
    from ._models import AvailableRPOperation  # type: ignore
    from ._models import AvailableRPOperationDisplayInfo  # type: ignore
    from ._models import BigDataPoolPatchInfo  # type: ignore
    from ._models import BigDataPoolResourceInfo  # type: ignore
    from ._models import BigDataPoolResourceInfoListResult  # type: ignore
    from ._models import CheckNameAvailabilityRequest  # type: ignore
    from ._models import CheckNameAvailabilityResponse  # type: ignore
    from ._models import CloudError  # type: ignore
    from ._models import CmdkeySetup  # type: ignore
    from ._models import ComponentSetup  # type: ignore
    from ._models import CreateSQLPoolRestorePointDefinition  # type: ignore
    from ._models import CustomSetupBase  # type: ignore
    from ._models import DataLakeStorageAccountDetails  # type: ignore
    from ._models import DataWarehouseUserActivities  # type: ignore
    from ._models import EntityReference  # type: ignore
    from ._models import EnvironmentVariableSetup  # type: ignore
    from ._models import ErrorAdditionalInfo  # type: ignore
    from ._models import ErrorContract  # type: ignore
    from ._models import ErrorDetail  # type: ignore
    from ._models import ErrorResponse  # type: ignore
    from ._models import GeoBackupPolicy  # type: ignore
    from ._models import GetSsisObjectMetadataRequest  # type: ignore
    from ._models import IntegrationRuntime  # type: ignore
    from ._models import IntegrationRuntimeAuthKeys  # type: ignore
    from ._models import IntegrationRuntimeComputeProperties  # type: ignore
    from ._models import IntegrationRuntimeConnectionInfo  # type: ignore
    from ._models import IntegrationRuntimeCustomSetupScriptProperties  # type: ignore
    from ._models import IntegrationRuntimeDataFlowProperties  # type: ignore
    from ._models import IntegrationRuntimeDataProxyProperties  # type: ignore
    from ._models import IntegrationRuntimeListResponse  # type: ignore
    from ._models import IntegrationRuntimeMonitoringData  # type: ignore
    from ._models import IntegrationRuntimeNodeIpAddress  # type: ignore
    from ._models import IntegrationRuntimeNodeMonitoringData  # type: ignore
    from ._models import IntegrationRuntimeRegenerateKeyParameters  # type: ignore
    from ._models import IntegrationRuntimeResource  # type: ignore
    from ._models import IntegrationRuntimeSsisCatalogInfo  # type: ignore
    from ._models import IntegrationRuntimeSsisProperties  # type: ignore
    from ._models import IntegrationRuntimeStatus  # type: ignore
    from ._models import IntegrationRuntimeStatusResponse  # type: ignore
    from ._models import IntegrationRuntimeVNetProperties  # type: ignore
    from ._models import IpFirewallRuleInfo  # type: ignore
    from ._models import IpFirewallRuleInfoListResult  # type: ignore
    from ._models import IpFirewallRuleProperties  # type: ignore
    from ._models import LibraryRequirements  # type: ignore
    from ._models import LinkedIntegrationRuntime  # type: ignore
    from ._models import LinkedIntegrationRuntimeKeyAuthorization  # type: ignore
    from ._models import LinkedIntegrationRuntimeRbacAuthorization  # type: ignore
    from ._models import LinkedIntegrationRuntimeType  # type: ignore
    from ._models import ManagedIdentity  # type: ignore
    from ._models import ManagedIdentitySQLControlSettingsModel  # type: ignore
    from ._models import ManagedIdentitySQLControlSettingsModelPropertiesGrantSQLControlToManagedIdentity  # type: ignore
    from ._models import ManagedIntegrationRuntime  # type: ignore
    from ._models import ManagedIntegrationRuntimeError  # type: ignore
    from ._models import ManagedIntegrationRuntimeNode  # type: ignore
    from ._models import ManagedIntegrationRuntimeOperationResult  # type: ignore
    from ._models import ManagedIntegrationRuntimeStatus  # type: ignore
    from ._models import MetadataSyncConfig  # type: ignore
    from ._models import OperationMetaLogSpecification  # type: ignore
    from ._models import OperationMetaMetricDimensionSpecification  # type: ignore
    from ._models import OperationMetaMetricSpecification  # type: ignore
    from ._models import OperationMetaServiceSpecification  # type: ignore
    from ._models import OperationResource  # type: ignore
    from ._models import PrivateEndpoint  # type: ignore
    from ._models import PrivateEndpointConnection  # type: ignore
    from ._models import PrivateEndpointConnectionList  # type: ignore
    from ._models import PrivateLinkHub  # type: ignore
    from ._models import PrivateLinkHubInfoListResult  # type: ignore
    from ._models import PrivateLinkHubPatchInfo  # type: ignore
    from ._models import PrivateLinkResource  # type: ignore
    from ._models import PrivateLinkResourceListResult  # type: ignore
    from ._models import PrivateLinkResourceProperties  # type: ignore
    from ._models import PrivateLinkServiceConnectionState  # type: ignore
    from ._models import ProxyResource  # type: ignore
    from ._models import QueryInterval  # type: ignore
    from ._models import QueryMetric  # type: ignore
    from ._models import QueryStatistic  # type: ignore
    from ._models import ReplaceAllFirewallRulesOperationResponse  # type: ignore
    from ._models import ReplaceAllIpFirewallRulesRequest  # type: ignore
    from ._models import ReplicationLink  # type: ignore
    from ._models import ReplicationLinkListResult  # type: ignore
    from ._models import Resource  # type: ignore
    from ._models import ResourceMoveDefinition  # type: ignore
    from ._models import RestorePoint  # type: ignore
    from ._models import RestorePointListResult  # type: ignore
    from ._models import SQLPool  # type: ignore
    from ._models import SQLPoolBlobAuditingPolicy  # type: ignore
    from ._models import SQLPoolBlobAuditingPolicySQLPoolOperationListResult  # type: ignore
    from ._models import SQLPoolColumn  # type: ignore
    from ._models import SQLPoolColumnListResult  # type: ignore
    from ._models import SQLPoolConnectionPolicy  # type: ignore
    from ._models import SQLPoolInfoListResult  # type: ignore
    from ._models import SQLPoolOperation  # type: ignore
    from ._models import SQLPoolPatchInfo  # type: ignore
    from ._models import SQLPoolSchema  # type: ignore
    from ._models import SQLPoolSchemaListResult  # type: ignore
    from ._models import SQLPoolSecurityAlertPolicy  # type: ignore
    from ._models import SQLPoolTable  # type: ignore
    from ._models import SQLPoolTableListResult  # type: ignore
    from ._models import SQLPoolUsage  # type: ignore
    from ._models import SQLPoolUsageListResult  # type: ignore
    from ._models import SQLPoolVulnerabilityAssessment  # type: ignore
    from ._models import SQLPoolVulnerabilityAssessmentListResult  # type: ignore
    from ._models import SQLPoolVulnerabilityAssessmentRuleBaseline  # type: ignore
    from ._models import SQLPoolVulnerabilityAssessmentRuleBaselineItem  # type: ignore
    from ._models import SQLPoolVulnerabilityAssessmentScansExport  # type: ignore
    from ._models import SecretBase  # type: ignore
    from ._models import SecureString  # type: ignore
    from ._models import SelfHostedIntegrationRuntime  # type: ignore
    from ._models import SelfHostedIntegrationRuntimeNode  # type: ignore
    from ._models import SelfHostedIntegrationRuntimeStatus  # type: ignore
    from ._models import SensitivityLabel  # type: ignore
    from ._models import SensitivityLabelListResult  # type: ignore
    from ._models import Sku  # type: ignore
    from ._models import SsisEnvironment  # type: ignore
    from ._models import SsisEnvironmentReference  # type: ignore
    from ._models import SsisFolder  # type: ignore
    from ._models import SsisObjectMetadata  # type: ignore
    from ._models import SsisObjectMetadataListResponse  # type: ignore
    from ._models import SsisObjectMetadataStatusResponse  # type: ignore
    from ._models import SsisPackage  # type: ignore
    from ._models import SsisParameter  # type: ignore
    from ._models import SsisProject  # type: ignore
    from ._models import SsisVariable  # type: ignore
    from ._models import SubResource  # type: ignore
    from ._models import TopQueries  # type: ignore
    from ._models import TopQueriesListResult  # type: ignore
    from ._models import TrackedResource  # type: ignore
    from ._models import TransparentDataEncryption  # type: ignore
    from ._models import UpdateIntegrationRuntimeNodeRequest  # type: ignore
    from ._models import UpdateIntegrationRuntimeRequest  # type: ignore
    from ._models import VirtualNetworkProfile  # type: ignore
    from ._models import VulnerabilityAssessmentRecurringScansProperties  # type: ignore
    from ._models import VulnerabilityAssessmentScanError  # type: ignore
    from ._models import VulnerabilityAssessmentScanRecord  # type: ignore
    from ._models import VulnerabilityAssessmentScanRecordListResult  # type: ignore
    from ._models import Workspace  # type: ignore
    from ._models import WorkspaceAADAdminInfo  # type: ignore
    from ._models import WorkspaceInfoListResult  # type: ignore
    from ._models import WorkspacePatchInfo  # type: ignore

from ._synapse_management_client_enums import (
    BlobAuditingPolicyState,
    ColumnDataType,
    ConnectionPolicyName,
    DataFlowComputeType,
    DataWarehouseUserActivityName,
    GeoBackupPolicyName,
    GeoBackupPolicyState,
    IntegrationRuntimeAuthKeyName,
    IntegrationRuntimeAutoUpdate,
    IntegrationRuntimeEdition,
    IntegrationRuntimeEntityReferenceType,
    IntegrationRuntimeInternalChannelEncryptionMode,
    IntegrationRuntimeLicenseType,
    IntegrationRuntimeSsisCatalogPricingTier,
    IntegrationRuntimeState,
    IntegrationRuntimeType,
    IntegrationRuntimeUpdateResult,
    ManagedIdentitySQLControlSettingsModelPropertiesGrantSQLControlToManagedIdentityActualState,
    ManagedIdentitySQLControlSettingsModelPropertiesGrantSQLControlToManagedIdentityDesiredState,
    ManagedIntegrationRuntimeNodeStatus,
    ManagementOperationState,
    NodeSize,
    NodeSizeFamily,
    OperationStatus,
    PrivateLinkHubPropertiesProvisioningState,
    PrivateLinkServiceConnectionStateStatus,
    ProvisioningState,
    QueryAggregationFunction,
    QueryExecutionType,
    QueryMetricUnit,
    QueryObservedMetricType,
    ReplicationRole,
    ReplicationState,
    ResourceIdentityType,
    RestorePointType,
    SecurityAlertPolicyName,
    SecurityAlertPolicyState,
    SelfHostedIntegrationRuntimeNodeStatus,
    SsisObjectMetadataType,
    TransparentDataEncryptionName,
    TransparentDataEncryptionStatus,
    VulnerabilityAssessmentName,
    VulnerabilityAssessmentPolicyBaselineName,
    VulnerabilityAssessmentScanState,
    VulnerabilityAssessmentScanTriggerType,
)

__all__ = [
    'AutoPauseProperties',
    'AutoScaleProperties',
    'AvailableRPOperation',
    'AvailableRPOperationDisplayInfo',
    'BigDataPoolPatchInfo',
    'BigDataPoolResourceInfo',
    'BigDataPoolResourceInfoListResult',
    'CheckNameAvailabilityRequest',
    'CheckNameAvailabilityResponse',
    'CloudError',
    'CmdkeySetup',
    'ComponentSetup',
    'CreateSQLPoolRestorePointDefinition',
    'CustomSetupBase',
    'DataLakeStorageAccountDetails',
    'DataWarehouseUserActivities',
    'EntityReference',
    'EnvironmentVariableSetup',
    'ErrorAdditionalInfo',
    'ErrorContract',
    'ErrorDetail',
    'ErrorResponse',
    'GeoBackupPolicy',
    'GetSsisObjectMetadataRequest',
    'IntegrationRuntime',
    'IntegrationRuntimeAuthKeys',
    'IntegrationRuntimeComputeProperties',
    'IntegrationRuntimeConnectionInfo',
    'IntegrationRuntimeCustomSetupScriptProperties',
    'IntegrationRuntimeDataFlowProperties',
    'IntegrationRuntimeDataProxyProperties',
    'IntegrationRuntimeListResponse',
    'IntegrationRuntimeMonitoringData',
    'IntegrationRuntimeNodeIpAddress',
    'IntegrationRuntimeNodeMonitoringData',
    'IntegrationRuntimeRegenerateKeyParameters',
    'IntegrationRuntimeResource',
    'IntegrationRuntimeSsisCatalogInfo',
    'IntegrationRuntimeSsisProperties',
    'IntegrationRuntimeStatus',
    'IntegrationRuntimeStatusResponse',
    'IntegrationRuntimeVNetProperties',
    'IpFirewallRuleInfo',
    'IpFirewallRuleInfoListResult',
    'IpFirewallRuleProperties',
    'LibraryRequirements',
    'LinkedIntegrationRuntime',
    'LinkedIntegrationRuntimeKeyAuthorization',
    'LinkedIntegrationRuntimeRbacAuthorization',
    'LinkedIntegrationRuntimeType',
    'ManagedIdentity',
    'ManagedIdentitySQLControlSettingsModel',
    'ManagedIdentitySQLControlSettingsModelPropertiesGrantSQLControlToManagedIdentity',
    'ManagedIntegrationRuntime',
    'ManagedIntegrationRuntimeError',
    'ManagedIntegrationRuntimeNode',
    'ManagedIntegrationRuntimeOperationResult',
    'ManagedIntegrationRuntimeStatus',
    'MetadataSyncConfig',
    'OperationMetaLogSpecification',
    'OperationMetaMetricDimensionSpecification',
    'OperationMetaMetricSpecification',
    'OperationMetaServiceSpecification',
    'OperationResource',
    'PrivateEndpoint',
    'PrivateEndpointConnection',
    'PrivateEndpointConnectionList',
    'PrivateLinkHub',
    'PrivateLinkHubInfoListResult',
    'PrivateLinkHubPatchInfo',
    'PrivateLinkResource',
    'PrivateLinkResourceListResult',
    'PrivateLinkResourceProperties',
    'PrivateLinkServiceConnectionState',
    'ProxyResource',
    'QueryInterval',
    'QueryMetric',
    'QueryStatistic',
    'ReplaceAllFirewallRulesOperationResponse',
    'ReplaceAllIpFirewallRulesRequest',
    'ReplicationLink',
    'ReplicationLinkListResult',
    'Resource',
    'ResourceMoveDefinition',
    'RestorePoint',
    'RestorePointListResult',
    'SQLPool',
    'SQLPoolBlobAuditingPolicy',
    'SQLPoolBlobAuditingPolicySQLPoolOperationListResult',
    'SQLPoolColumn',
    'SQLPoolColumnListResult',
    'SQLPoolConnectionPolicy',
    'SQLPoolInfoListResult',
    'SQLPoolOperation',
    'SQLPoolPatchInfo',
    'SQLPoolSchema',
    'SQLPoolSchemaListResult',
    'SQLPoolSecurityAlertPolicy',
    'SQLPoolTable',
    'SQLPoolTableListResult',
    'SQLPoolUsage',
    'SQLPoolUsageListResult',
    'SQLPoolVulnerabilityAssessment',
    'SQLPoolVulnerabilityAssessmentListResult',
    'SQLPoolVulnerabilityAssessmentRuleBaseline',
    'SQLPoolVulnerabilityAssessmentRuleBaselineItem',
    'SQLPoolVulnerabilityAssessmentScansExport',
    'SecretBase',
    'SecureString',
    'SelfHostedIntegrationRuntime',
    'SelfHostedIntegrationRuntimeNode',
    'SelfHostedIntegrationRuntimeStatus',
    'SensitivityLabel',
    'SensitivityLabelListResult',
    'Sku',
    'SsisEnvironment',
    'SsisEnvironmentReference',
    'SsisFolder',
    'SsisObjectMetadata',
    'SsisObjectMetadataListResponse',
    'SsisObjectMetadataStatusResponse',
    'SsisPackage',
    'SsisParameter',
    'SsisProject',
    'SsisVariable',
    'SubResource',
    'TopQueries',
    'TopQueriesListResult',
    'TrackedResource',
    'TransparentDataEncryption',
    'UpdateIntegrationRuntimeNodeRequest',
    'UpdateIntegrationRuntimeRequest',
    'VirtualNetworkProfile',
    'VulnerabilityAssessmentRecurringScansProperties',
    'VulnerabilityAssessmentScanError',
    'VulnerabilityAssessmentScanRecord',
    'VulnerabilityAssessmentScanRecordListResult',
    'Workspace',
    'WorkspaceAADAdminInfo',
    'WorkspaceInfoListResult',
    'WorkspacePatchInfo',
    'BlobAuditingPolicyState',
    'ColumnDataType',
    'ConnectionPolicyName',
    'DataFlowComputeType',
    'DataWarehouseUserActivityName',
    'GeoBackupPolicyName',
    'GeoBackupPolicyState',
    'IntegrationRuntimeAuthKeyName',
    'IntegrationRuntimeAutoUpdate',
    'IntegrationRuntimeEdition',
    'IntegrationRuntimeEntityReferenceType',
    'IntegrationRuntimeInternalChannelEncryptionMode',
    'IntegrationRuntimeLicenseType',
    'IntegrationRuntimeSsisCatalogPricingTier',
    'IntegrationRuntimeState',
    'IntegrationRuntimeType',
    'IntegrationRuntimeUpdateResult',
    'ManagedIdentitySQLControlSettingsModelPropertiesGrantSQLControlToManagedIdentityActualState',
    'ManagedIdentitySQLControlSettingsModelPropertiesGrantSQLControlToManagedIdentityDesiredState',
    'ManagedIntegrationRuntimeNodeStatus',
    'ManagementOperationState',
    'NodeSize',
    'NodeSizeFamily',
    'OperationStatus',
    'PrivateLinkHubPropertiesProvisioningState',
    'PrivateLinkServiceConnectionStateStatus',
    'ProvisioningState',
    'QueryAggregationFunction',
    'QueryExecutionType',
    'QueryMetricUnit',
    'QueryObservedMetricType',
    'ReplicationRole',
    'ReplicationState',
    'ResourceIdentityType',
    'RestorePointType',
    'SecurityAlertPolicyName',
    'SecurityAlertPolicyState',
    'SelfHostedIntegrationRuntimeNodeStatus',
    'SsisObjectMetadataType',
    'TransparentDataEncryptionName',
    'TransparentDataEncryptionStatus',
    'VulnerabilityAssessmentName',
    'VulnerabilityAssessmentPolicyBaselineName',
    'VulnerabilityAssessmentScanState',
    'VulnerabilityAssessmentScanTriggerType',
]
