trigger:
- master

variables:
  NodeVersion: '10.x'
  VAR_BUILD_ARTIFACT_STAGING_DIRECTORY: $(Build.ArtifactStagingDirectory)
  VAR_ARIFACT_NAME: "drop"
  parallelTest: 'true'

jobs:
  - job: ESLint
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - task: Npm@1
        displayName: 'npm install'
        inputs:
          verbose: false
      - script: 'node_modules\.bin\eslint . --ext .ts --ignore-pattern node_modules/ --ignore-pattern dist/'
        displayName: 'eslint'

  - job: Build
    pool:
      vmImage: 'Ubuntu 16.04'
      pythonVersion: '3.6'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '$(NodeVersion)'
        displayName: 'Install Node.js $(NodeVersion)'
      - task: Npm@1
        displayName: 'npm install'
        inputs:
          verbose: false
      - task: UsePythonVersion@0
        displayName: 'Use Python 3.6'
        inputs:
          versionSpec: 3.6
      - script: 'npm run build'
        displayName: 'npm build'
      - script: 'npm test'
        displayName: 'npm test'
      - script: 'npm pack'
        displayName: 'npm pack'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(VAR_BUILD_ARTIFACT_STAGING_DIRECTORY)'
          ArtifactName: '$(VAR_ARIFACT_NAME)'
          publishLocation: 'Container'

  - job: Analyze
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '$(NodeVersion)'
        displayName: 'Install Node.js $(NodeVersion)'
      - task: Npm@1
        displayName: 'npm install'
        inputs:
          command: install
      - task: Npm@1
        displayName: 'npm audit'
        condition: and(succeeded(), eq(variables['RunNpmAudit'], 'true'))
        inputs:
          command: custom
          customCommand: 'audit'

  - job: Windows
    displayName: CredScan
    pool:
      vmImage: "windows-2019"
    steps:
      - task:  ea576cd4-c61f-48f8-97e7-a3cb07b90a6f@3
        inputs:
          toolMajorVersion: 'V1'
      - task: f5679091-e6da-4974-a8dc-0eec03a8ea63@1
        inputs:
          AllTools: false
          APIScan: false
          BinSkim: false
          CodesignValidation: false
          CredScan: true
          FortifySCA: false
          FxCop: false
          ModernCop: false
          PoliCheck: false
          RoslynAnalyzers: false
          SDLNativeRules: false
          Semmle: false
          TSLint: false
          ToolLogsNotFoundAction: 'Standard'