trigger:
- master

variables:
  NodeVersion: '10.x'

jobs:
#  - job: Linter
#    pool:
#      vmImage: 'vs2017-win2016'
#    steps:
#      - task: TSLint@1
#        inputs:
#          RuleLibrary: 'tslint'
#          Ruleset: 'tsrecommended'
#          FileSelectionType: 'fileGlob'
#          Files: '**\*.ts'
#          OutputFormat: 'json'
#          ToolVersion: 'latest'
#          TypeScriptVersion: 'latest'

  - job: 'Build'

    pool:
      vmImage: 'Ubuntu 16.04'
      pythonVersion: '3.6'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '$(NodeVersion)'
        displayName: 'Install Node.js $(NodeVersion)'

      - task: Npm@1
        displayName: 'npm install'
        inputs:
          verbose: false

      - task: UsePythonVersion@0
        displayName: 'Use Python 3.6'
        inputs:
          versionSpec: 3.6

      - script: 'npx @microsoft/rush sync-versions && npx @microsoft/rush update && npx @microsoft/rush rebuild'
        displayName: 'npm build'

      - script: 'npm test'
        displayName: 'npm test'

      - script: 'npx @microsoft/rush publish --publish --pack --include-all --tag latest'
        displayName: 'npm pack'

  - job: 'Analyze'

    pool:
      vmImage: 'Ubuntu 16.04'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '$(NodeVersion)'
        displayName: 'Install Node.js $(NodeVersion)'

      - task: Npm@1
        displayName: 'npm install'
        inputs:
          command: install

      - task: Npm@1
        displayName: 'npm audit'
        condition: and(succeeded(), eq(variables['RunNpmAudit'], 'true'))
        inputs:
          command: custom
          customCommand: 'audit'

#  - job: Windows
#    displayName: credentialScan
#    pool:
#      vmImage: "windows-2019"

#    steps:
#      - task:  CredScan@3
#        inputs:
#          toolMajorVersion: 'V1'
#      - task: PostAnalysis@1
#        inputs:
#          AllTools: false
#          APIScan: false
#          BinSkim: false
#          CodesignValidation: false
#          CredScan: true
#          FortifySCA: false
#          FxCop: false
#          ModernCop: false
#          PoliCheck: false
#          RoslynAnalyzers: false
#          SDLNativeRules: false
#          Semmle: false
#          TSLint: false
#          ToolLogsNotFoundAction: 'Standard'

